# Exercises - Data Aquistion

[*Codeup Lesson*](https://ds.codeup.com/9-timeseries/2-acquire/)

All of the exercises for this module should be done within your `ds-methodologies` repository, inside of a directory named `time_series`.

The end result of this exercise should be a file named `acquire.py`.

In [1]:
from pprint import pprint
import requests
import pandas as pd
import json

from os import path

In [2]:
from debug import local_settings, timeifdebug, timeargsifdebug, frame_splain

import acquire as acq

In [3]:
local_settings.debug = True

1. **Using the code from the lesson as a guide, create a dataframe named `items` that has all of the data for items.**

2. **Do the same thing, but for `stores`.**

3. **Extract the data for `sales`. There are a lot of pages of data here, so your code will need to be a little more complex. Your code should continue fetching data from the next page until all of the data is extracted.**

4. **Save the data in your files to local csv files so that it will be faster to access in the future.**

5. **Combine the data from your three separate dataframes into one large dataframe.**

In [4]:
base_url = 'https://python.zach.lol'

In [5]:
sect_urls = {
    'items': {
        'sect_key': 'items', 
        'api_url': '/api/v1/items',
        'idx_col': 'item_id', 
        'page_beg': 1,
        'csv_name': 'items.csv'
    },
    'stores': {
        'sect_key': 'stores', 
        'api_url': '/api/v1/stores', 
        'idx_col': 'store_id', 
        'page_beg': 1, 
        'csv_name': 'stores.csv'
    },
    'sales': {
        'sect_key': 'sales', 
        'api_url': '/api/v1/sales', 
        'idx_col': 'sale_id', 
        'page_beg': 1, 
        'csv_name': 'sales.csv'
    },
}

In [6]:
def get_val_from_key(dict, key='key', keys=None):
    if keys is None:
        keys = dict.keys()
    return dict[key] if key in keys else None

In [7]:
def get_json_payload_data(
    target_table='items',
    base_url='https://python.zach.lol',
    sect_key='items',
    api_url='/api/v1/items',
    idx_col='item_id',
    beg_page=1,
    csv_name='items.csv',
    data_key='payload',
    status_key='status',
    on_page_key='page',
    of_pages_key='max_page',
    url_next_key='next_page',
    url_prev_key='previous_page',
    url_get_page='?page=',
    sep=',',
    to_csv=False,
    show_log=False,
    ):
    
    # Setup df
    df = pd.DataFrame()

    # Initialize variables
    cur_page = beg_page
    pages_max = -1
    keep_going = True
    
    # Get initial page
    next_url = api_url
    while keep_going:
        is_complete = False
        get_url = base_url + next_url
        
        # Get webpage
        if show_log:
            print('Fetching page', get_url)
        response = requests.get(get_url)
        
        # Get JSON data
        response_json = response.json()
        json_keys = response_json.keys()
        
        # Get payload
        payload = get_val_from_key(dict=response_json, key=data_key, keys=json_keys)
        if payload is None:
            break

        payload_keys = payload.keys()
        
        # Set navigation values
        on_page = get_val_from_key(dict=payload, key=on_page_key, keys=payload_keys)
        of_pages = get_val_from_key(dict=payload, key=of_pages_key, keys=payload_keys)
        url_next = get_val_from_key(dict=payload, key=url_next_key, keys=payload_keys)
        url_prev = get_val_from_key(dict=payload, key=url_prev_key, keys=payload_keys)
        
        # Get target data
        target_data = get_val_from_key(dict=payload, key=sect_key, keys=payload_keys)
        if target_data is None:
            break
        
        # Make page dataframe
        page_df = pd.DataFrame(target_data)
        if idx_col in page_df.columns:
            page_df.set_index(idx_col, inplace=True)
        else:
            print('index is missing')
            break
        
        df = df.append(page_df, verify_integrity=True)

        if url_next is None:
            keep_going = False
            
        if keep_going:
            next_url = url_next
        else:
            next_url = None
        
        is_complete = True
        
    if to_csv:
        df.to_csv(
            path_or_buf=csv_name, 
            sep=sep, 
            index=True, 
            index_label=idx_col, 
        )
        
    return df

In [8]:
def output_payload_data(
    target_table='items', 
    base_url='https://python.zach.lol',
    to_csv=False,
    show_log=False,
    sect_url_keys=sect_urls,
    sep=',',
    **kwargs):
    
    url_keys = sect_url_keys[target_table]
    sect_key = url_keys['sect_key']
    api_url = url_keys['api_url']
    idx_col = url_keys['idx_col']
    beg_page=url_keys['page_beg']
    csv_name=url_keys['csv_name']
    
    df = get_json_payload_data(
        target_table=target_table,
        base_url=base_url,
        sect_key=sect_key,
        api_url=api_url,
        idx_col=idx_col,
        beg_page=beg_page,
        csv_name=csv_name,
        data_key='payload',
        status_key='status',
        on_page_key='page',
        of_pages_key='max_page',
        url_next_key='next_page',
        url_prev_key='previous_page',
        url_get_page='?page=',
        sep=sep,
        to_csv=to_csv,
        show_log=show_log,
    )
    
    return df

In [9]:
items_df = acq.output_payload_data(
    target_table='items', 
    base_url=base_url, 
    to_csv=True,
    show_log=True,
    sect_url_keys=sect_urls,
    sep=',',
    debug=True
)

2019-11-13 22:22:54 starting output_payload_data
2019-11-13 22:22:54 starting get_json_payload_data
Fetching page https://python.zach.lol/api/v1/items
Fetching page https://python.zach.lol/api/v1/items?page=2
Fetching page https://python.zach.lol/api/v1/items?page=3
2019-11-13 22:22:55 ending get_json_payload_data ; time: 0:00:00.966151
2019-11-13 22:22:55 ending output_payload_data ; time: 0:00:00.966734

In [10]:
stores_df = acq.output_payload_data(
    target_table='stores', 
    base_url=base_url, 
    to_csv=True,
    show_log=True,
    sect_url_keys=sect_urls,
    sep=',',
    debug=True
)

2019-11-13 22:22:55 starting output_payload_data
2019-11-13 22:22:55 starting get_json_payload_data
Fetching page https://python.zach.lol/api/v1/stores
2019-11-13 22:22:55 ending get_json_payload_data ; time: 0:00:00.306791
2019-11-13 22:22:55 ending output_payload_data ; time: 0:00:00.311423

In [11]:
sales_df = acq.output_payload_data(
    target_table='sales', 
    base_url=base_url, 
    to_csv=True,
    show_log=True,
    sect_url_keys=sect_urls,
    sep=',',
    debug=True
)

2019-11-13 22:22:55 starting output_payload_data
2019-11-13 22:22:55 starting get_json_payload_data
Fetching page https://python.zach.lol/api/v1/sales
Fetching page https://python.zach.lol/api/v1/sales?page=2
Fetching page https://python.zach.lol/api/v1/sales?page=3
Fetching page https://python.zach.lol/api/v1/sales?page=4
Fetching page https://python.zach.lol/api/v1/sales?page=5
Fetching page https://python.zach.lol/api/v1/sales?page=6
Fetching page https://python.zach.lol/api/v1/sales?page=7
Fetching page https://python.zach.lol/api/v1/sales?page=8
Fetching page https://python.zach.lol/api/v1/sales?page=9
Fetching page https://python.zach.lol/api/v1/sales?page=10
Fetching page https://python.zach.lol/api/v1/sales?page=11
Fetching page https://python.zach.lol/api/v1/sales?page=12
Fetching page https://python.zach.lol/api/v1/sales?page=13
Fetching page https://python.zach.lol/api/v1/sales?page=14
Fetching page https://python.zach.lol/api/v1/sales?page=15
Fetching page https://python.zach.lol/api/v1/sales?page=16
Fetching page https://python.zach.lol/api/v1/sales?page=17
Fetching page https://python.zach.lol/api/v1/sales?page=18
Fetching page https://python.zach.lol/api/v1/sales?page=19
Fetching page https://python.zach.lol/api/v1/sales?page=20
Fetching page https://python.zach.lol/api/v1/sales?page=21
Fetching page https://python.zach.lol/api/v1/sales?page=22
Fetching page https://python.zach.lol/api/v1/sales?page=23
Fetching page https://python.zach.lol/api/v1/sales?page=24
Fetching page https://python.zach.lol/api/v1/sales?page=25
Fetching page https://python.zach.lol/api/v1/sales?page=26
Fetching page https://python.zach.lol/api/v1/sales?page=27
Fetching page https://python.zach.lol/api/v1/sales?page=28
Fetching page https://python.zach.lol/api/v1/sales?page=29
Fetching page https://python.zach.lol/api/v1/sales?page=30
Fetching page https://python.zach.lol/api/v1/sales?page=31
Fetching page https://python.zach.lol/api/v1/sales?page=32
Fetching page https://python.zach.lol/api/v1/sales?page=33
Fetching page https://python.zach.lol/api/v1/sales?page=34
Fetching page https://python.zach.lol/api/v1/sales?page=35
Fetching page https://python.zach.lol/api/v1/sales?page=36
Fetching page https://python.zach.lol/api/v1/sales?page=37
Fetching page https://python.zach.lol/api/v1/sales?page=38
Fetching page https://python.zach.lol/api/v1/sales?page=39
Fetching page https://python.zach.lol/api/v1/sales?page=40
Fetching page https://python.zach.lol/api/v1/sales?page=41
Fetching page https://python.zach.lol/api/v1/sales?page=42
Fetching page https://python.zach.lol/api/v1/sales?page=43
Fetching page https://python.zach.lol/api/v1/sales?page=44
Fetching page https://python.zach.lol/api/v1/sales?page=45
Fetching page https://python.zach.lol/api/v1/sales?page=46
Fetching page https://python.zach.lol/api/v1/sales?page=47
Fetching page https://python.zach.lol/api/v1/sales?page=48
Fetching page https://python.zach.lol/api/v1/sales?page=49
Fetching page https://python.zach.lol/api/v1/sales?page=50
Fetching page https://python.zach.lol/api/v1/sales?page=51
Fetching page https://python.zach.lol/api/v1/sales?page=52
Fetching page https://python.zach.lol/api/v1/sales?page=53
Fetching page https://python.zach.lol/api/v1/sales?page=54
Fetching page https://python.zach.lol/api/v1/sales?page=55
Fetching page https://python.zach.lol/api/v1/sales?page=56
Fetching page https://python.zach.lol/api/v1/sales?page=57
Fetching page https://python.zach.lol/api/v1/sales?page=58
Fetching page https://python.zach.lol/api/v1/sales?page=59
Fetching page https://python.zach.lol/api/v1/sales?page=60
Fetching page https://python.zach.lol/api/v1/sales?page=61
Fetching page https://python.zach.lol/api/v1/sales?page=62
Fetching page https://python.zach.lol/api/v1/sales?page=63
Fetching page https://python.zach.lol/api/v1/sales?page=64
Fetching page https://python.zach.lol/api/v1/sales?page=65
Fetching page https://python.zach.lol/api/v1/sales?page=66
Fetching page https://python.zach.lol/api/v1/sales?page=67
Fetching page https://python.zach.lol/api/v1/sales?page=68
Fetching page https://python.zach.lol/api/v1/sales?page=69
Fetching page https://python.zach.lol/api/v1/sales?page=70
Fetching page https://python.zach.lol/api/v1/sales?page=71
Fetching page https://python.zach.lol/api/v1/sales?page=72
Fetching page https://python.zach.lol/api/v1/sales?page=73
Fetching page https://python.zach.lol/api/v1/sales?page=74
Fetching page https://python.zach.lol/api/v1/sales?page=75
Fetching page https://python.zach.lol/api/v1/sales?page=76
Fetching page https://python.zach.lol/api/v1/sales?page=77
Fetching page https://python.zach.lol/api/v1/sales?page=78
Fetching page https://python.zach.lol/api/v1/sales?page=79
Fetching page https://python.zach.lol/api/v1/sales?page=80
Fetching page https://python.zach.lol/api/v1/sales?page=81
Fetching page https://python.zach.lol/api/v1/sales?page=82
Fetching page https://python.zach.lol/api/v1/sales?page=83
Fetching page https://python.zach.lol/api/v1/sales?page=84
Fetching page https://python.zach.lol/api/v1/sales?page=85
Fetching page https://python.zach.lol/api/v1/sales?page=86
Fetching page https://python.zach.lol/api/v1/sales?page=87
Fetching page https://python.zach.lol/api/v1/sales?page=88
Fetching page https://python.zach.lol/api/v1/sales?page=89
Fetching page https://python.zach.lol/api/v1/sales?page=90
Fetching page https://python.zach.lol/api/v1/sales?page=91
Fetching page https://python.zach.lol/api/v1/sales?page=92
Fetching page https://python.zach.lol/api/v1/sales?page=93
Fetching page https://python.zach.lol/api/v1/sales?page=94
Fetching page https://python.zach.lol/api/v1/sales?page=95
Fetching page https://python.zach.lol/api/v1/sales?page=96
Fetching page https://python.zach.lol/api/v1/sales?page=97
Fetching page https://python.zach.lol/api/v1/sales?page=98
Fetching page https://python.zach.lol/api/v1/sales?page=99
Fetching page https://python.zach.lol/api/v1/sales?page=100
Fetching page https://python.zach.lol/api/v1/sales?page=101
Fetching page https://python.zach.lol/api/v1/sales?page=102
Fetching page https://python.zach.lol/api/v1/sales?page=103
Fetching page https://python.zach.lol/api/v1/sales?page=104
Fetching page https://python.zach.lol/api/v1/sales?page=105
Fetching page https://python.zach.lol/api/v1/sales?page=106
Fetching page https://python.zach.lol/api/v1/sales?page=107
Fetching page https://python.zach.lol/api/v1/sales?page=108
Fetching page https://python.zach.lol/api/v1/sales?page=109
Fetching page https://python.zach.lol/api/v1/sales?page=110
Fetching page https://python.zach.lol/api/v1/sales?page=111
Fetching page https://python.zach.lol/api/v1/sales?page=112
Fetching page https://python.zach.lol/api/v1/sales?page=113
Fetching page https://python.zach.lol/api/v1/sales?page=114
Fetching page https://python.zach.lol/api/v1/sales?page=115
Fetching page https://python.zach.lol/api/v1/sales?page=116
Fetching page https://python.zach.lol/api/v1/sales?page=117
Fetching page https://python.zach.lol/api/v1/sales?page=118
Fetching page https://python.zach.lol/api/v1/sales?page=119
Fetching page https://python.zach.lol/api/v1/sales?page=120
Fetching page https://python.zach.lol/api/v1/sales?page=121
Fetching page https://python.zach.lol/api/v1/sales?page=122
Fetching page https://python.zach.lol/api/v1/sales?page=123
Fetching page https://python.zach.lol/api/v1/sales?page=124
Fetching page https://python.zach.lol/api/v1/sales?page=125
Fetching page https://python.zach.lol/api/v1/sales?page=126
Fetching page https://python.zach.lol/api/v1/sales?page=127
Fetching page https://python.zach.lol/api/v1/sales?page=128
Fetching page https://python.zach.lol/api/v1/sales?page=129
Fetching page https://python.zach.lol/api/v1/sales?page=130
Fetching page https://python.zach.lol/api/v1/sales?page=131
Fetching page https://python.zach.lol/api/v1/sales?page=132
Fetching page https://python.zach.lol/api/v1/sales?page=133
Fetching page https://python.zach.lol/api/v1/sales?page=134
Fetching page https://python.zach.lol/api/v1/sales?page=135
Fetching page https://python.zach.lol/api/v1/sales?page=136
Fetching page https://python.zach.lol/api/v1/sales?page=137

Fetching page https://python.zach.lol/api/v1/sales?page=138
Fetching page https://python.zach.lol/api/v1/sales?page=139
Fetching page https://python.zach.lol/api/v1/sales?page=140
Fetching page https://python.zach.lol/api/v1/sales?page=141
Fetching page https://python.zach.lol/api/v1/sales?page=142
Fetching page https://python.zach.lol/api/v1/sales?page=143
Fetching page https://python.zach.lol/api/v1/sales?page=144
Fetching page https://python.zach.lol/api/v1/sales?page=145
Fetching page https://python.zach.lol/api/v1/sales?page=146
Fetching page https://python.zach.lol/api/v1/sales?page=147
Fetching page https://python.zach.lol/api/v1/sales?page=148
Fetching page https://python.zach.lol/api/v1/sales?page=149
Fetching page https://python.zach.lol/api/v1/sales?page=150
Fetching page https://python.zach.lol/api/v1/sales?page=151
Fetching page https://python.zach.lol/api/v1/sales?page=152
Fetching page https://python.zach.lol/api/v1/sales?page=153
Fetching page https://python.zach.lol/api/v1/sales?page=154
Fetching page https://python.zach.lol/api/v1/sales?page=155
Fetching page https://python.zach.lol/api/v1/sales?page=156
Fetching page https://python.zach.lol/api/v1/sales?page=157
Fetching page https://python.zach.lol/api/v1/sales?page=158
Fetching page https://python.zach.lol/api/v1/sales?page=159
Fetching page https://python.zach.lol/api/v1/sales?page=160
Fetching page https://python.zach.lol/api/v1/sales?page=161
Fetching page https://python.zach.lol/api/v1/sales?page=162
Fetching page https://python.zach.lol/api/v1/sales?page=163
Fetching page https://python.zach.lol/api/v1/sales?page=164
Fetching page https://python.zach.lol/api/v1/sales?page=165
Fetching page https://python.zach.lol/api/v1/sales?page=166
Fetching page https://python.zach.lol/api/v1/sales?page=167
Fetching page https://python.zach.lol/api/v1/sales?page=168
Fetching page https://python.zach.lol/api/v1/sales?page=169
Fetching page https://python.zach.lol/api/v1/sales?page=170
Fetching page https://python.zach.lol/api/v1/sales?page=171
Fetching page https://python.zach.lol/api/v1/sales?page=172
Fetching page https://python.zach.lol/api/v1/sales?page=173
Fetching page https://python.zach.lol/api/v1/sales?page=174
Fetching page https://python.zach.lol/api/v1/sales?page=175
Fetching page https://python.zach.lol/api/v1/sales?page=176
Fetching page https://python.zach.lol/api/v1/sales?page=177
Fetching page https://python.zach.lol/api/v1/sales?page=178
Fetching page https://python.zach.lol/api/v1/sales?page=179
Fetching page https://python.zach.lol/api/v1/sales?page=180
Fetching page https://python.zach.lol/api/v1/sales?page=181
Fetching page https://python.zach.lol/api/v1/sales?page=182
Fetching page https://python.zach.lol/api/v1/sales?page=183
2019-11-13 22:30:42 ending get_json_payload_data ; time: 0:07:46.135273
2019-11-13 22:30:42 ending output_payload_data ; time: 0:07:46.136479

In [12]:
sales_df.head()

         item  sale_amount                      sale_date  store
sale_id
1           1         13.0  Tue, 01 Jan 2013 00:00:00 GMT      1
2           1         11.0  Wed, 02 Jan 2013 00:00:00 GMT      1
3           1         14.0  Thu, 03 Jan 2013 00:00:00 GMT      1
4           1         13.0  Fri, 04 Jan 2013 00:00:00 GMT      1
5           1         10.0  Sat, 05 Jan 2013 00:00:00 GMT      1

In [13]:
sales_df.item.value_counts()

50    18260
13    18260
23    18260
22    18260
21    18260
20    18260
19    18260
18    18260
17    18260
16    18260
15    18260
14    18260
12    18260
49    18260
11    18260
10    18260
9     18260
8     18260
7     18260
6     18260
5     18260
4     18260
3     18260
2     18260
24    18260
25    18260
26    18260
27    18260
48    18260
47    18260
46    18260
45    18260
44    18260
43    18260
42    18260
41    18260
40    18260
39    18260
38    18260
37    18260
36    18260
35    18260
34    18260
33    18260
32    18260
31    18260
30    18260
29    18260
28    18260
1     18260
Name: item, dtype: int64

In [14]:
sales_df.sale_date.value_counts()

Thu, 28 Jan 2016 00:00:00 GMT    500
Sat, 20 Jul 2013 00:00:00 GMT    500
Fri, 10 Apr 2015 00:00:00 GMT    500
Fri, 05 Jul 2013 00:00:00 GMT    500
Mon, 04 Apr 2016 00:00:00 GMT    500
Mon, 30 Oct 2017 00:00:00 GMT    500
Sat, 19 Nov 2016 00:00:00 GMT    500
Sat, 05 Apr 2014 00:00:00 GMT    500
Mon, 01 May 2017 00:00:00 GMT    500
Tue, 08 Dec 2015 00:00:00 GMT    500
Tue, 21 Apr 2015 00:00:00 GMT    500
Wed, 25 Sep 2013 00:00:00 GMT    500
Tue, 26 Nov 2013 00:00:00 GMT    500
Fri, 24 Jan 2014 00:00:00 GMT    500
Mon, 02 Mar 2015 00:00:00 GMT    500
Wed, 11 Jun 2014 00:00:00 GMT    500
Sun, 09 Apr 2017 00:00:00 GMT    500
Wed, 13 Aug 2014 00:00:00 GMT    500
Wed, 02 Mar 2016 00:00:00 GMT    500
Tue, 26 Dec 2017 00:00:00 GMT    500
Sat, 29 Jul 2017 00:00:00 GMT    500
Mon, 11 Apr 2016 00:00:00 GMT    500
Thu, 03 Oct 2013 00:00:00 GMT    500
Thu, 29 May 2014 00:00:00 GMT    500
Fri, 06 Nov 2015 00:00:00 GMT    500
Wed, 05 Oct 2016 00:00:00 GMT    500
Mon, 09 Mar 2015 00:00:00 GMT    500
Mon, 06 Jul 2015 00:00:00 GMT    500
Tue, 09 Feb 2016 00:00:00 GMT    500
Wed, 28 Oct 2015 00:00:00 GMT    500
                                ...
Thu, 11 Dec 2014 00:00:00 GMT    500
Fri, 07 Nov 2014 00:00:00 GMT    500
Tue, 16 May 2017 00:00:00 GMT    500
Thu, 05 Oct 2017 00:00:00 GMT    500
Tue, 07 Jun 2016 00:00:00 GMT    500
Mon, 27 Jan 2014 00:00:00 GMT    500
Thu, 23 May 2013 00:00:00 GMT    500
Thu, 30 Apr 2015 00:00:00 GMT    500
Tue, 25 Oct 2016 00:00:00 GMT    500
Wed, 07 May 2014 00:00:00 GMT    500
Thu, 21 Nov 2013 00:00:00 GMT    500
Tue, 15 Jan 2013 00:00:00 GMT    500
Wed, 27 Jul 2016 00:00:00 GMT    500
Thu, 03 Nov 2016 00:00:00 GMT    500
Fri, 27 Nov 2015 00:00:00 GMT    500
Wed, 08 Jul 2015 00:00:00 GMT    500
Sat, 24 Dec 2016 00:00:00 GMT    500
Mon, 20 Apr 2015 00:00:00 GMT    500
Wed, 27 Jan 2016 00:00:00 GMT    500
Sat, 22 Oct 2016 00:00:00 GMT    500
Fri, 30 Jan 2015 00:00:00 GMT    500
Wed, 11 Sep 2013 00:00:00 GMT    500
Sat, 30 Mar 2013 00:00:00 GMT    500
Wed, 29 Mar 2017 00:00:00 GMT    500
Sun, 24 Feb 2013 00:00:00 GMT    500
Sun, 09 Nov 2014 00:00:00 GMT    500
Thu, 24 Dec 2015 00:00:00 GMT    500
Fri, 29 May 2015 00:00:00 GMT    500
Tue, 24 May 2016 00:00:00 GMT    500
Mon, 22 May 2017 00:00:00 GMT    500
Name: sale_date, Length: 1826, dtype: int64

In [15]:
sales_df.store.value_counts()

10    91300
9     91300
8     91300
7     91300
6     91300
5     91300
4     91300
3     91300
2     91300
1     91300
Name: store, dtype: int64

In [20]:
combo_df = sales_df.merge(items_df, how='outer', left_on='item', right_on='item_id', validate='m:1')
combo_df.sample(20)

,item,sale_amount,sale_date,store,item_brand,item_name,item_price,item_upc12,item_upc14
911352,50,62.0,"Fri, 28 Jun 2013 00:00:00 GMT",10,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221
200432,11,93.0,"Sun, 30 Oct 2016 00:00:00 GMT",10,Honest Tea,Honest Tea Peach White Tea,3.93,657622604842,657622604842
23241,2,59.0,"Mon, 22 Aug 2016 00:00:00 GMT",3,Caress,Caress Velvet Bliss Ultra Silkening Beauty Bar...,6.44,11111065925,11111065925
408710,23,25.0,"Tue, 21 Feb 2017 00:00:00 GMT",4,Reese,Reese Mandarin Oranges Segments In Light Syrup,1.78,70670009658,70670009658
772152,43,67.0,"Sun, 30 Apr 2017 00:00:00 GMT",3,Ferrara,Ferrara Vanilla Syrup,8.40,71403000379,71403000379
899983,50,103.0,"Thu, 11 May 2017 00:00:00 GMT",3,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221
58367,4,39.0,"Sat, 28 Oct 2017 00:00:00 GMT",2,Boars Head,Boars Head Sliced White American Cheese - 120 Ct,3.14,208528800007,208528800007
691081,38,76.0,"Mon, 04 May 2015 00:00:00 GMT",9,Sundown Naturals,Sundown Naturals Essential Electrolytes Tropic...,3.45,30768540548,30768540548
22871,2,86.0,"Tue, 18 Aug 2015 00:00:00 GMT",3,Caress,Caress Velvet Bliss Ultra Silkening Beauty Bar...,6.44,11111065925,11111065925
312360,18,101.0,"Thu, 25 Apr 2013 00:00:00 GMT",2,Scotch,Scotch Removable Clear Mounting Squares - 35 Ct,4.39,21200725340,21200725340
896661,50,76.0,"Sat, 06 Apr 2013 00:00:00 GMT",2,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221
572506,32,54.0,"Thu, 27 Aug 2015 00:00:00 GMT",4,Barefoot,Barefoot Pinot Grigio 187,0.68,8500004528,8500004528
677519,38,81.0,"Fri, 15 Mar 2013 00:00:00 GMT",2,Sundown Naturals,Sundown Naturals Essential Electrolytes Tropic...,3.45,30768540548,30768540548
459026,26,42.0,"Tue, 02 Dec 2014 00:00:00 GMT",2,Triaminic,Triaminic Syrup Night Time Cold & Cough Grape 4oz,0.98,300436344045,300436344045
405757,23,19.0,"Tue, 21 Jan 2014 00:00:00 GMT",3,Reese,Reese Mandarin Oranges Segments In Light Syrup,1.78,70670009658,70670009658
596881,33,59.0,"Thu, 25 May 2017 00:00:00 GMT",7,The First Years,Tomy The First Years Gumdrop Orthodontic Pacif...,6.52,71463060078,71463060078
107182,6,66.0,"Tue, 28 Jun 2016 00:00:00 GMT",9,Sally Hansen,Sally Hansen Nail Color Magnetic 903 Silver El...,6.93,74170388732,74170388732
450482,25,81.0,"Sun, 10 Jul 2016 00:00:00 GMT",7,Hood,Hood Latte Iced Coffee Drink Vanilla Latte,2.43,44100117428,44100117428
184168,11,67.0,"Tue, 18 Apr 2017 00:00:00 GMT",1,Honest Tea,Honest Tea Peach White Tea,3.93,657622604842,657622604842
48237,3,20.0,"Sun, 01 Feb 2015 00:00:00 GMT",7,Earths Best,Earths Best Organic Fruit Yogurt Smoothie Mixe...,2.43,23923330139,23923330139

In [21]:
combo_df = combo_df.merge(stores_df, how='outer', left_on='store', right_on='store_id', validate='m:1')
combo_df.sample(20)

,item,sale_amount,sale_date,store,item_brand,item_name,item_price,item_upc12,item_upc14,store_address,store_city,store_state,store_zipcode
225607,24,63.0,"Wed, 07 Oct 2015 00:00:00 GMT",3,Smart Living,Smart Living Charcoal Lighter Fluid,5.34,688267084225,688267084225,2118 Fredericksburg Rdj,San Antonio,TX,78201
891524,39,37.0,"Thu, 13 Mar 2014 00:00:00 GMT",10,Munchies,Munchies Sandwich Crackers Cheddar Cheese On G...,9.02,28400029254,28400029254,8503 NW Military Hwy,San Antonio,TX,78231
578247,17,22.0,"Mon, 16 May 2016 00:00:00 GMT",7,Ducal,Ducal Refried Red Beans,1.16,88313590791,88313590791,12018 Perrin Beitel Rd,San Antonio,TX,78217
553192,3,33.0,"Sat, 07 Oct 2017 00:00:00 GMT",7,Earths Best,Earths Best Organic Fruit Yogurt Smoothie Mixe...,2.43,23923330139,23923330139,12018 Perrin Beitel Rd,San Antonio,TX,78217
637436,50,40.0,"Wed, 12 Jun 2013 00:00:00 GMT",7,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221,12018 Perrin Beitel Rd,San Antonio,TX,78217
714144,42,50.0,"Fri, 28 Jun 2013 00:00:00 GMT",8,Moms Best Naturals,Moms Best Naturals Cereal Toasted Cinnamon Squ...,2.97,883978129115,883978129115,15000 San Pedro Ave,San Antonio,TX,78232
691415,29,111.0,"Sat, 02 Apr 2016 00:00:00 GMT",8,Heinz,Heinz Tomato Ketchup - 2 Ct,8.65,13000001038,13000001038,15000 San Pedro Ave,San Antonio,TX,78232
232927,28,108.0,"Fri, 23 Oct 2015 00:00:00 GMT",3,Usda Produce,Guava,7.52,719175900007,719175900007,2118 Fredericksburg Rdj,San Antonio,TX,78201
627712,44,18.0,"Wed, 26 Oct 2016 00:00:00 GMT",7,Elmers,Elmers Board Mate Dual Tip Glue Pen,7.06,26000001403,26000001403,12018 Perrin Beitel Rd,San Antonio,TX,78217
203832,12,69.0,"Sun, 21 Feb 2016 00:00:00 GMT",3,Mueller,Mueller Sport Care Basic Support Level Medium ...,8.40,74676640211,74676640211,2118 Fredericksburg Rdj,San Antonio,TX,78201
263120,45,87.0,"Wed, 26 Jun 2013 00:00:00 GMT",3,Kelloggs,Kelloggs Disney Pixar Cars 2 Cereal,4.40,38000542237,38000542237,2118 Fredericksburg Rdj,San Antonio,TX,78201
418487,30,29.0,"Sat, 30 Nov 2013 00:00:00 GMT",5,Petmate,Petmate Booda Bones Steak Bacon & Chicken Flav...,8.39,723503568678,723503568678,1520 Austin Hwy,San Antonio,TX,78218
587393,22,60.0,"Wed, 01 Jun 2016 00:00:00 GMT",7,Betty Crocker,Betty Crocker Twin Pack Real Potatoes Scallope...,7.31,16000288829,16000288829,12018 Perrin Beitel Rd,San Antonio,TX,78217
531756,42,25.0,"Sun, 26 Jan 2014 00:00:00 GMT",6,Moms Best Naturals,Moms Best Naturals Cereal Toasted Cinnamon Squ...,2.97,883978129115,883978129115,1015 S WW White Rd,San Antonio,TX,78220
421417,31,34.0,"Thu, 08 Dec 2016 00:00:00 GMT",5,Zhenas Gypsy Tea,Zhenas Gypsy Tea Herbal Red Tea Sachets Fire L...,4.21,652790100226,652790100226,1520 Austin Hwy,San Antonio,TX,78218
623893,42,20.0,"Thu, 12 May 2016 00:00:00 GMT",7,Moms Best Naturals,Moms Best Naturals Cereal Toasted Cinnamon Squ...,2.97,883978129115,883978129115,12018 Perrin Beitel Rd,San Antonio,TX,78217
664169,14,63.0,"Wed, 24 Aug 2016 00:00:00 GMT",8,Pamprin,Pamprin Maximum Strength Multi-symptom Menstru...,7.54,41167300121,41167300121,15000 San Pedro Ave,San Antonio,TX,78232
512177,31,66.0,"Wed, 17 Jun 2015 00:00:00 GMT",6,Zhenas Gypsy Tea,Zhenas Gypsy Tea Herbal Red Tea Sachets Fire L...,4.21,652790100226,652790100226,1015 S WW White Rd,San Antonio,TX,78220
731722,1,13.0,"Mon, 15 Aug 2016 00:00:00 GMT",9,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013,735 SW Military Dr,San Antonio,TX,78221
242493,33,56.0,"Sun, 01 Jan 2017 00:00:00 GMT",3,The First Years,Tomy The First Years Gumdrop Orthodontic Pacif...,6.52,71463060078,71463060078,2118 Fredericksburg Rdj,San Antonio,TX,78201

In [22]:
frame_splain(combo_df, splain=True)

2019-11-14 10:15:12 starting frame_splain
DATAFRAME SHAPE:
(913000, 13)

DATAFRAME INFO:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 913000 entries, 0 to 912999
Data columns (total 13 columns):
item             913000 non-null int64
sale_amount      913000 non-null float64
sale_date        913000 non-null object
store            913000 non-null int64
item_brand       913000 non-null object
item_name        913000 non-null object
item_price       913000 non-null float64
item_upc12       913000 non-null object
item_upc14       913000 non-null object
store_address    913000 non-null object
store_city       913000 non-null object
store_state      913000 non-null object
store_zipcode    913000 non-null object
dtypes: float64(2), int64(2), object(9)
memory usage: 97.5+ MB
None

DATAFRAME DESCRIPTION:
                count       mean        std  min    25%     50%    75%     max
item         913000.0  25.500000  14.430878  1.0  13.00  25.500  38.00   50.00
sale_amount  913000.0  52.250287  28.801144  0.0  30.00  47.000  70.00  231.00
store        913000.0   5.500000   2.872283  1.0   3.00   5.500   8.00   10.00
item_price   913000.0   5.160400   2.737764  0.6   2.97   5.195   7.52    9.64

2019-11-14 10:15:13 ending frame_splain ; time: 0:00:00.795511

In [1]:
combo_df.index.rename('sales_id')

NameError: name 'combo_df' is not defined

6. **Acquire the Open Power Systems Data for Germany, which has been rapidly expanding its renewable energy production in recent years. The data set includes country-wide totals of electricity consumption, wind power production, and solar power production for 2006-2017. You can get the data here:** https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv

In [16]:
### shamelessly stolen from zach:
from os import path

def get_opsd_data(use_cache=True):
    if use_cache and path.exists('opsd.csv'):
        return pd.read_csv('opsd.csv')
    df = pd.read_csv('https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv')
    df.to_csv('opsd.csv', index=False)
    return df

In [17]:
opsd_df = get_opsd_data()
opsd_df

            Date  Consumption     Wind   Solar  Wind+Solar
0     2006-01-01   1069.18400      NaN     NaN         NaN
1     2006-01-02   1380.52100      NaN     NaN         NaN
2     2006-01-03   1442.53300      NaN     NaN         NaN
3     2006-01-04   1457.21700      NaN     NaN         NaN
4     2006-01-05   1477.13100      NaN     NaN         NaN
5     2006-01-06   1403.42700      NaN     NaN         NaN
6     2006-01-07   1300.28700      NaN     NaN         NaN
7     2006-01-08   1207.98500      NaN     NaN         NaN
8     2006-01-09   1529.32300      NaN     NaN         NaN
9     2006-01-10   1576.91100      NaN     NaN         NaN
10    2006-01-11   1577.17600      NaN     NaN         NaN
11    2006-01-12   1553.28000      NaN     NaN         NaN
12    2006-01-13   1545.00200      NaN     NaN         NaN
13    2006-01-14   1359.94500      NaN     NaN         NaN
14    2006-01-15   1265.47500      NaN     NaN         NaN
15    2006-01-16   1563.73800      NaN     NaN         NaN
16    2006-01-17   1598.30300      NaN     NaN         NaN
17    2006-01-18   1572.98400      NaN     NaN         NaN
18    2006-01-19   1558.29000      NaN     NaN         NaN
19    2006-01-20   1540.60400      NaN     NaN         NaN
20    2006-01-21   1348.18800      NaN     NaN         NaN
21    2006-01-22   1248.11100      NaN     NaN         NaN
22    2006-01-23   1569.69100      NaN     NaN         NaN
23    2006-01-24   1603.25200      NaN     NaN         NaN
24    2006-01-25   1613.31200      NaN     NaN         NaN
25    2006-01-26   1601.67300      NaN     NaN         NaN
26    2006-01-27   1586.06500      NaN     NaN         NaN
27    2006-01-28   1373.03000      NaN     NaN         NaN
28    2006-01-29   1252.21500      NaN     NaN         NaN
29    2006-01-30   1554.72200      NaN     NaN         NaN
...          ...          ...      ...     ...         ...
4353  2017-12-02   1391.85405  126.274  16.459     142.733
4354  2017-12-03   1330.26226  387.490  12.411     399.901
4355  2017-12-04   1620.97758  479.798  10.747     490.545
4356  2017-12-05   1643.72307  611.488  10.953     622.441
4357  2017-12-06   1639.08265  632.501   7.618     640.119
4358  2017-12-07   1628.47979  743.725  42.994     786.719
4359  2017-12-08   1618.05658  652.830  20.504     673.334
4360  2017-12-09   1415.34531  712.317  12.344     724.661
4361  2017-12-10   1318.10964  622.944   9.922     632.866
4362  2017-12-11   1614.15862  415.109   5.669     420.778
4363  2017-12-12   1647.36346  590.101  13.250     603.351
4364  2017-12-13   1651.90418  721.540  36.880     758.420
4365  2017-12-14   1636.54375  666.438  21.030     687.468
4366  2017-12-15   1576.93197  176.418  21.653     198.071
4367  2017-12-16   1382.87708  277.391  15.904     293.295
4368  2017-12-17   1297.21916  250.726  12.620     263.346
4369  2017-12-18   1578.69079  134.843  15.897     150.740
4370  2017-12-19   1586.48230   99.098   8.793     107.891
4371  2017-12-20   1559.68569   90.880   8.799      99.679
4372  2017-12-21   1520.37206  259.039   7.313     266.352
4373  2017-12-22   1423.23782  228.773  10.065     238.838
4374  2017-12-23   1272.17085  748.074   8.450     756.524
4375  2017-12-24   1141.75730  812.422   9.949     822.371
4376  2017-12-25   1111.28338  587.810  15.765     603.575
4377  2017-12-26   1130.11683  717.453  30.923     748.376
4378  2017-12-27   1263.94091  394.507  16.530     411.037
4379  2017-12-28   1299.86398  506.424  14.162     520.586
4380  2017-12-29   1295.08753  584.277  29.854     614.131
4381  2017-12-30   1215.44897  721.247   7.467     728.714
4382  2017-12-31   1107.11488  721.176  19.980     741.156

[4383 rows x 5 columns]

7. **Make sure all the work that you have done above is reproducible. That is, you should put the code above into separate functions in the `acquire.py` file and be able to re-run the functions and get the same data.**